version: '3.8'

services:
  mongo:
    image: mongo:6.0
    container_name: mordor-parking-control-mongo
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db

  api:
    build:
      context: .
    container_name: mordor-parking-control-api
    ports:
      - "3000:3000"
    depends_on:
      - mongo
    environment:
      - MONGO_URI=mongodb://mongo:27017/mordor_parking_control
    volumes:
      - .:/app
    command: npx nodemon index.js

volumes:
  mongo-data:
